import { EnvelopeIcon } from "@sanity/icons/Envelope";
import { defineArrayMember, defineField, defineType } from "sanity";
import { str, txt } from "../helpers";

export default defineType({
  name: "contactSection",
  title: "Contact section",
  type: "document",
  icon: EnvelopeIcon,
  groups: [
    { name: "heading", title: "Heading", default: true },
    { name: "labels", title: "Labels" },
    { name: "form", title: "Note form" },
    { name: "footer", title: "Footer" },
  ],
  fields: [
    str("indexLabel", "Index label", "The small number above the heading, e.g. “(04)”.", { group: "heading", max: 8 }),
    str("headingCaps", "Heading, line 1 (capitals)", "The first line of the big heading, shown in bold capitals, e.g. “Got an idea?”.", { group: "heading", required: true, max: 24 }),
    str("headingItalic", "Heading, line 2 (italic)", "The second line, shown in serif italic, e.g. “Say hi.”.", { group: "heading", required: true, max: 24 }),
    defineField({
      name: "labels",
      title: "Labels",
      type: "object",
      group: "labels",
      description: "The small captions around your email and social buttons.",
      options: { collapsible: false },
      fields: [
        str("email", "Email caption", "Small caption above your email address.", { required: true, max: 20, initialValue: "Email" }),
        str("elsewhere", "Socials caption", "Small caption above the social icons.", { required: true, max: 20, initialValue: "Elsewhere" }),
        str("locationLine", "Location line", "e.g. “Based in Bandra, Mumbai”.", { max: 50 }),
        str("replyLine", "Reply-time line", "Write {time} where the live clock should appear, e.g. “{time} IST · usually replies within two days”.", { max: 70 }),
        str("copy", "Copy button", "Button that copies your email. Brackets are added for you.", { required: true, max: 24, initialValue: "Copy email" }),
        str("copied", "Copy confirmation", "Shown for a moment after the email is copied.", { required: true, max: 24, initialValue: "Copied" }),
        str("copyFallback", "Copy fallback", "Shown if the browser blocks copying and the address is selected instead.", { required: true, max: 40, initialValue: "Selected, press Ctrl+C" }),
      ],
    }),
    defineField({
      name: "form",
      title: "Note form",
      type: "object",
      group: "form",
      description: "Every word on the contact form, from the title to the error messages.",
      options: { collapsible: false },
      fields: [
        str("titleLead", "Title, first part", "Plain half of the form title, e.g. “Or leave a note”.", { required: true, max: 30 }),
        str("titleItalic", "Title, italic part", "Italic half of the form title, e.g. “right here.”.", { required: true, max: 30 }),
        str("topicLegend", "Topic question", "The question above the topic buttons.", { required: true, max: 40 }),
        defineField({
          name: "topics",
          title: "Topic options",
          type: "array",
          description: "The buttons a visitor picks from. The first one is selected by default. The value goes into the email subject. Drag to reorder.",
          of: [
            defineArrayMember({
              type: "object",
              name: "topic",
              title: "Topic",
              fields: [
                str("label", "Button text", "What the button says.", { required: true, max: 24 }),
                str("value", "Value in the email", "What appears in the email subject. Leave the same as the button text if unsure.", { required: true, max: 24 }),
              ],
              preview: { select: { title: "label", subtitle: "value" } },
            }),
          ],
          validation: (rule) => rule.required().min(1).max(6),
        }),
        str("nameLabel", "Name field label", "Label above the name box.", { required: true, max: 24 }),
        str("emailLabel", "Email field label", "Label above the email box.", { required: true, max: 24 }),
        str("messageLabel", "Message field label", "Label above the message box.", { required: true, max: 24 }),
        str("messagePlaceholder", "Message placeholder", "Grey hint text inside the empty message box.", { max: 60 }),
        str("idleStatus", "Helper line", "The small line beside the send button before anything is sent.", { max: 60 }),
        str("sendLabel", "Send button", "Text on the send button.", { required: true, max: 24 }),
        str("sendingLabel", "Sending button", "Text on the button while the note is being sent.", { required: true, max: 24 }),
        str("retryLabel", "Retry button", "Text on the button after a failed attempt.", { required: true, max: 24 }),
        str("sendingStatus", "Sending message", "The helper line while sending.", { max: 60 }),
        str("nameError", "Name error", "Shown when the name is missing or too short.", { required: true, max: 80 }),
        str("emailError", "Email error", "Shown when the email address doesn't look right.", { required: true, max: 80 }),
        str("messageError", "Message error", "Shown when the message is empty or too short.", { required: true, max: 80 }),
        str("successKicker", "Success caption", "Small caption above the thank-you message.", { required: true, max: 30 }),
        str("successTitle", "Success title", "Headline after a successful send. Write {name} to include the visitor's first name, e.g. “Thanks, {name}.”.", { required: true, max: 60 }),
        txt("successBody", "Success message", "The sentence under the thank-you headline.", { rows: 2, max: 120 }),
        str("writeAnotherLabel", "Write another button", "Button that returns to a blank form. Brackets are added for you.", { required: true, max: 24 }),
        txt("errorText", "Error message", "Shown when sending fails. Write {email} to include your email address.", { rows: 2, required: true, max: 140 }),
      ],
    }),
    defineField({
      name: "footer",
      title: "Footer",
      type: "object",
      group: "footer",
      description: "The very bottom of the page.",
      options: { collapsible: false },
      fields: [
        str("signature", "Signature", "The giant name that spans the page above the footer line, e.g. “Pranav.”.", { required: true, max: 12 }),
        str("copyright", "Copyright line", "Small print at the bottom left.", { max: 90 }),
        str("backToTopLabel", "Back to top button", "Button that scrolls to the top. Brackets are added for you.", { required: true, max: 24 }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Contact section" }) },
});
